spring.application.name=accounts

spring.autoconfigure.exclude= \
  org.springframework.boot.validation.autoconfigure.ValidationAutoConfiguration, \
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration, \
  org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfiguration
